{{- if .Values.postgresql.enableOperator }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "activepieces.fullname" . }}-postgresql
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
spec:
  instances: 1

  bootstrap:
    initdb:
      database: {{ .Values.postgresql.auth.database }}
      owner: {{ .Values.postgresql.auth.username }}
      secret:
        name: postgresql-{{ include "activepieces.fullname" . }}-{{ .Values.postgresql.auth.username }}
{{- if .Values.postgresql.primary.persistence.enabled }}
  storage:
    size: {{ default "8Gi" .Values.postgresql.primary.persistence.size }}
    storageClass: {{ .Values.postgresql.primary.persistence.storageClass }}
{{- end }}
{{- end }}
