apiVersion: v1
kind: Secret
metadata:
  name: postgresql-{{ include "activepieces.fullname" . }}-{{ .Values.postgresql.auth.username }}
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
  annotations:
    {{- if or (.Capabilities.APIVersions.Has "secretgenerator.mittwald.de/v1alpha1/BasicAuth") (not (eq (index .Values "kubernetes-secret-generator" "enabled") false)) }}
    secret-generator.v1.mittwald.de/autogenerate: encryption-key
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
    {{- end }}
type: kubernetes.io/basic-auth
{{- if or (.Capabilities.APIVersions.Has "secretgenerator.mittwald.de/v1alpha1/BasicAuth") (not (eq (index .Values "kubernetes-secret-generator" "enabled") false)) }}
data: {}
{{- else }}
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ default (randAlphaNum 10) .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}

